const eventData = [
  {
    event_name: "Bronx Summer Sounds",
    artist: "The Skyline Notes",
    borough: "Bronx",
    stadium: "Yankee Stadium",
    address: "1 E. 161st St., Bronx, NY 10451",
    event_date: "April 12, 2026",
    start_time: "7:30 PM",
    genre: "Pop",
    description:
      "A spring pop concert at Yankee Stadium featuring upbeat city-inspired music.",
    ticket_price: "$85",
    image: "pop-concert.jpg",
    status: "Past",
  },
  {
    event_name: "Reggaeton Night at Yankee Stadium",
    artist: "Luna Fuego",
    borough: "Bronx",
    stadium: "Yankee Stadium",
    address: "1 E. 161st St., Bronx, NY 10451",
    event_date: "July 20, 2026",
    start_time: "8:00 PM",
    genre: "Latin / Reggaeton",
    description:
      "A high-energy reggaeton concert bringing Latin music fans together in the Bronx.",
    ticket_price: "$120",
    image: "reggaeton-concert.jpg",
    status: "Upcoming",
  },
  {
    event_name: "Classic Rock Bronx Fest",
    artist: "Hudson River Rebels",
    borough: "Bronx",
    stadium: "Yankee Stadium",
    address: "1 E. 161st St., Bronx, NY 10451",
    event_date: "August 15, 2026",
    start_time: "6:30 PM",
    genre: "Rock",
    description:
      "A classic rock stadium show with guitar-heavy performances and a full light show.",
    ticket_price: "$95",
    image: "rock-concert.jpg",
    status: "Upcoming",
  },

  {
    event_name: "Brooklyn R&B Live",
    artist: "Maya Rivers",
    borough: "Brooklyn",
    stadium: "Barclays Center",
    address: "620 Atlantic Ave., Brooklyn, NY 11217",
    event_date: "May 2, 2026",
    start_time: "8:00 PM",
    genre: "R&B",
    description:
      "A smooth R&B concert night featuring vocals, live instruments, and Brooklyn energy.",
    ticket_price: "$75",
    image: "rnb-concert.jpg",
    status: "Past",
  },
  {
    event_name: "Brooklyn Bass Drop",
    artist: "DJ Metro Pulse",
    borough: "Brooklyn",
    stadium: "Barclays Center",
    address: "620 Atlantic Ave., Brooklyn, NY 11217",
    event_date: "June 28, 2026",
    start_time: "9:00 PM",
    genre: "EDM",
    description:
      "An electronic dance concert with heavy bass, lasers, and a packed arena crowd.",
    ticket_price: "$65",
    image: "edm-concert.jpg",
    status: "Upcoming",
  },
  {
    event_name: "The Borough Tour",
    artist: "Nova Hart",
    borough: "Brooklyn",
    stadium: "Barclays Center",
    address: "620 Atlantic Ave., Brooklyn, NY 11217",
    event_date: "September 5, 2026",
    start_time: "8:30 PM",
    genre: "Pop",
    description:
      "A major pop tour stop at Barclays Center with dancers, visuals, and live vocals.",
    ticket_price: "$110",
    image: "pop-tour-concert.jpg",
    status: "Upcoming",
  },
  {
    event_name: "Brooklyn Indie Showcase",
    artist: "The Sidewalk Echoes",
    borough: "Brooklyn",
    stadium: "Barclays Center",
    address: "620 Atlantic Ave., Brooklyn, NY 11217",
    event_date: "October 3, 2026",
    start_time: "7:00 PM",
    genre: "Indie Rock",
    description:
      "An indie rock showcase featuring rising bands from across New York City.",
    ticket_price: "$55",
    image: "indie-rock-concert.jpg",
    status: "Upcoming",
  },

  {
    event_name: "Queens Hip-Hop Night",
    artist: "King Avenue",
    borough: "Queens",
    stadium: "Citi Field",
    address: "41 Seaver Way, Queens, NY 11368",
    event_date: "April 25, 2026",
    start_time: "8:00 PM",
    genre: "Hip-Hop",
    description:
      "A Queens-centered hip-hop concert with local openers and a stadium headline set.",
    ticket_price: "$90",
    image: "hiphop-concert.jpg",
    status: "Past",
  },
  {
    event_name: "Citi Field Country Jam",
    artist: "Amber Plains",
    borough: "Queens",
    stadium: "Citi Field",
    address: "41 Seaver Way, Queens, NY 11368",
    event_date: "August 1, 2026",
    start_time: "6:00 PM",
    genre: "Country",
    description:
      "A summer country concert with acoustic sets, full-band performances, and food vendors.",
    ticket_price: "$70",
    image: "country-concert.jpg",
    status: "Upcoming",
  },

  {
    event_name: "Queens Night Court Concert",
    artist: "Electric Bloom",
    borough: "Queens",
    stadium: "USTA Billie Jean King National Tennis Center",
    address: "Flushing Meadows Corona Park, Queens, NY 11368",
    event_date: "July 11, 2026",
    start_time: "7:30 PM",
    genre: "Alternative",
    description:
      "An outdoor-style alternative concert hosted at one of Queens' most recognizable venues.",
    ticket_price: "$60",
    image: "alternative-concert.jpg",
    status: "Upcoming",
  },

  {
    event_name: "Uptown Rhythm Fest",
    artist: "Harlem Brass Collective",
    borough: "Manhattan",
    stadium: "Nike Track & Field Center at The Armory",
    address: "216 Fort Washington Ave., Manhattan, NY 10032",
    event_date: "September 18, 2026",
    start_time: "7:00 PM",
    genre: "Jazz / Funk",
    description:
      "An uptown concert experience mixing jazz, funk, brass, and community celebration.",
    ticket_price: "$40",
    image: "jazz-concert.jpg",
    status: "Upcoming",
  },

  {
    event_name: "Madison Square Pop Night",
    artist: "Avery Stone",
    borough: "Manhattan",
    stadium: "Madison Square Garden",
    address: "4 Pennsylvania Plaza, New York, NY 10001",
    event_date: "May 19, 2026",
    start_time: "8:00 PM",
    genre: "Pop",
    description:
      "A major pop concert at Madison Square Garden with a full arena production.",
    ticket_price: "$130",
    image: "pop-tour-concert.jpg",
    status: "Past",
  },
  {
    event_name: "Garden Rap Showcase",
    artist: "Eastside Legend",
    borough: "Manhattan",
    stadium: "Madison Square Garden",
    address: "4 Pennsylvania Plaza, New York, NY 10001",
    event_date: "July 30, 2026",
    start_time: "8:30 PM",
    genre: "Rap",
    description:
      "A headline rap concert with surprise guests and NYC-themed stage visuals.",
    ticket_price: "$115",
    image: "rap-concert.jpg",
    status: "Upcoming",
  },
  {
    event_name: "Acoustic Night at the Garden",
    artist: "Sofia Lane",
    borough: "Manhattan",
    stadium: "Madison Square Garden",
    address: "4 Pennsylvania Plaza, New York, NY 10001",
    event_date: "November 12, 2026",
    start_time: "7:30 PM",
    genre: "Acoustic / Singer-Songwriter",
    description:
      "A stripped-down acoustic performance in one of New York City's most famous arenas.",
    ticket_price: "$80",
    image: "acoustic-concert.jpg",
    status: "Upcoming",
  },

  {
    event_name: "Forest Hills Summer Stage",
    artist: "Neon Harbor",
    borough: "Queens",
    stadium: "Forest Hills Stadium",
    address: "1 Tennis Pl., Forest Hills, NY 11375",
    event_date: "June 10, 2026",
    start_time: "7:00 PM",
    genre: "Synth Pop",
    description:
      "A colorful synth pop concert at Forest Hills Stadium with summer festival energy.",
    ticket_price: "$68",
    image: "synth-pop-concert.jpg",
    status: "Past",
  },
  {
    event_name: "Queens Indie Night",
    artist: "The Orange Lines",
    borough: "Queens",
    stadium: "Forest Hills Stadium",
    address: "1 Tennis Pl., Forest Hills, NY 11375",
    event_date: "August 22, 2026",
    start_time: "7:30 PM",
    genre: "Indie",
    description:
      "An indie concert night featuring mellow vocals, guitar-driven sets, and outdoor vibes.",
    ticket_price: "$58",
    image: "indie-night-concert.jpg",
    status: "Upcoming",
  },
];

export default eventData;
